# Generated by Django 3.0.8 on 2020-07-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_persondata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonData',
        ),
    ]
